### ISSUE TITLE
How to add style to error message?

### ISSUE THREAD

**Issue by atif0075** [daleal/loveform#16]
How can I style the rendered error message by targeting it? It just renders in a <p> tag without any class or ID, then how can we target it to apply style?

**Comment by daleal** [comment]
Hi! First of all, thank you for opening an issue! I have been thinking about the class to use for the error component so it can be styled. This would include classes for every component of loveform. What do you think about the following scheme?

```html
<input class="l-input" />
<p class="l-input__error">Some sample error</p>
```
